steps:
  # Build Backend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/raahiroute/raahi-route-backend', './backend']
    id: 'build-backend'

  # Build Frontend Image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/raahiroute/raahi-route-frontend', './frontend']
    id: 'build-frontend'

images:
  - 'gcr.io/raahiroute/raahi-route-backend'
  - 'gcr.io/raahiroute/raahi-route-frontend'
